name: jiffy
description: Jiffy is a date dart package inspired by momentjs for parsing, manipulating and formatting dates
version: 6.2.0
homepage: https://github.com/jama5262/jiffy
repository: https://github.com/jama5262/jiffy
issue_tracker: https://github.com/jama5262/jiffy/issues
documentation: https://github.com/jama5262/jiffy/tree/master/doc

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  intl: ^0.18.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.16.5
  coverage: ^1.6.3
