name: jiffy
description: Jiffy is a Flutter (Android, IOS and Web) date time package for parsing, manipulating, querying and formatting dates and time
version: 6.4.3
homepage: https://github.com/jama5262/jiffy
repository: https://github.com/jama5262/jiffy
issue_tracker: https://github.com/jama5262/jiffy/issues
documentation: https://github.com/jama5262/jiffy/tree/master/doc

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  intl: ^0.20.2
  quiver: ^3.2.2

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
  coverage: ^1.6.3
